### ISSUE TITLE
Add fallback website option

### ISSUE THREAD

**Issue by AlphaC0de** [dt-wark/instanon#10]
May I suggest to add a secondary website other than [StorieSig](https://storiesig.com) as a fallback option? Maybe [InstaStories](https://insta-stories.ru) so that the script always works?

**Comment by kerogenesis** [comment]
Yeah, that's a good idea.

However, the insta-stories.ru server takes too long to process requests.
Soon I will change storiesig.com to more stable and faster insta-stories.com :)
